language: node_js
node_js:
- '9'
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
- npm install -g @angular/cli
script:
- ng test --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
- ng lint
- npm run sonar
- ng build --output-path=last-build/ --configuration=production --base-href https://gurv.github.io/vg/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: last-build/
  on:
    branch: master
notifications:
  slack:
    secure: au0jv4k8UypJ+MEu4rFavgQ2G7p6TXYj7VOGh5TQeYaUeK7epHgJzNLoMgbvALlNWZkLDoBHkQO2YF1Vh1ozF1HenO8EXqof9wFXiAej/wd3PO05jcjamqRP1onRHiWx6vWxPqpGJDI3RpRgmnJuUIxmIH1JTbzK6hgGeDYZMqZN9l4RGQHkBF6dDw37Fco6u60QIK43Pl/DoGoTs91J3ZF+or/aBE5SMQdFR7WRIN/c3E0gwLxkDRdZGbdRoHAqh08MXUrXUMkKIWk1TYnvhCdy8AdUh3y1T2KsNi6FiHdF6UuBqu6RXkKn4L7sWRoMxJvcP4FDZwlug8GP296nozjznPeJeH6+90iNvpUFe6PSyYBaC2CTEZUlVZsgvUII+YUaI+oAt4zEmKLkT/eH74lAx5vXo7cU8vYNUebXmblKRXQWTEIaRQ6KjDwvJ7PYxboQavGcs/VdzNHowfod+1BWGGqi3tEUd04a+lXrONb9xlNg1hg5RjnFroIgkZH1tZgr4p3BqTXnwwzuY2S5JnQ05og4NqtAKDVy2AhfDUhT/Kp5IK7lAJ0svJYNxxfSVHvk1g8Tm+yI2QRoVH1SIqbPE8et6QpVDQdwO6f9/1i/DjnW8ZwWDfasO1/5LsxycTqsc9YokOqcw/+9q0XrnwnlLRaTgWsVxeCmLh4dYoQ=
