name: GitHub CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: NodeJs
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install -g @angular/cli
    - run: sh -e /etc/init.d/xvfb start
    - run: ng test --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
      env:
        DISPLAY: ':99.0'
    - run: ng e2e
    - run: ng lint
