name: GitHub CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: NodeJs
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Angular CLI
      run: npm install -g @angular/cli
    # FIXME 'Can't open /etc/init.d/xvfb'
    # - run: sh -e /etc/init.d/xvfb start
    # - run: ng test --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
      # env:
        # DISPLAY: ':99.0'
    # FIXME 'Could not find module "@angular-devkit/build-angular"'
    # - name: E2E
      # run: ng e2e
    - name: Lint
      run: ng lint
